### ISSUE TITLE
Error encountered in tutorial

### ISSUE THREAD

**Issue by thibaultcha** [bytecodealliance/component-docs#161]
While doing the composition tutorial: I run the last command:

```
wac compose composition.wac -o final.wasm
```

And get:

```
error: failed to resolve document

  × failed to create registry client: no home registry registry server URL is configured
```

What does this mean?

**Comment by kate-goldenring** [comment]
@thibaultcha I can repro this error if all components are not put at the path expected by `wac` or explicitly declared inline. Please make sure you move all components to a local deps directory as explained in the [tutorial README](https://github.com/bytecodealliance/component-docs/blob/main/component-model/examples/tutorial/README.md#composing-with-the-wac-language). Otherwise `wac` will look for the components in a registry and find that none was configured. Please reopen this if you're still running into this issue.

**Comment by thibaultcha** [comment]
I have followed the tutorial word for word, so everything should be at the right place already:
```
$ ls
README.md  adder  calculator  command  composed.wasm  composition.wac  deps  final.wasm  jco  wit
$ tree deps
deps
└── docs
    ├── addr-impl.wasm
    ├── calculator-impl.wasm
    └── command-impl.wasm
```

Is this wrong?
