### ISSUE TITLE
Use `uv` for Python version management and package installation in docs

### ISSUE THREAD

**Issue by vados-cosmonic** [bytecodealliance/component-docs#167]
While `uv` is a relatively new effort in the python space, it is proving to be very popular and more importantly effective in consolidating many tools in the python ecosystem into one coherent porcelain.

It might be a good idea to adopt this in the Python docs, which likely means more efficient (and also thorough) documentation. For example right now, specifying an exact python version might be somewhat difficult (since installing/recommending a way to install python & related deps is hard other than pointing to the official docs)

`uv` seems to fill the gap well as a tool that we can depend on (especially if we start including example Python code in the actual repo)

**Comment by kate-goldenring** [comment]
[`uv`](https://github.com/astral-sh/uv) looks amazing, simplifying creating virtual envs and python version. Thanks for bringing it up -- I personally will start using it. That being said, i'd be hesitant to require users to use it and add it to documentation flows. If possible, i think it would make sense to add instructions on using it to implementation READMEs rather than in the language guide.

**Comment by vados-cosmonic** [comment]
Yeah `uv` is pretty amazing! Thanks for noting your thoughts here -- I'll close this for now
